@echo off
REM Auto-tuned config v27 (Optuna, score=1.1103)
REM Generated by scripts/auto_tune.py
REM Phase 26: shared_expert + aux_loss_free + expert_ortho + learnable_temp

cd /d E:\hypercoplexAI
call .venv\Scripts\activate.bat

python scripts\gpu_train.py ^
    --epochs 200 ^
    --hidden_dim 256 ^
    --num_experts 4 ^
    --num_domains 4 ^
    --soft_router ^
    --pretrained_encoder ^
    --shared_expert ^
    --aux_loss_free ^
    --expert_ortho ^
    --learnable_temperature ^
    --real_pairs E:\hypercoplexAI\data\real_pairs_v10.json ^
    --augment_factor 5 ^
    --lambda_pair 0.5 ^
    --lambda_sts 0.3 ^
    --lambda_iso 0.1 ^
    --lambda_routing 0.02 ^
    --lambda_memory 0.01 ^
    --lambda_z 0.01 ^
    --lambda_dcl 0.2 ^
    --lambda_uniformity 0.1 ^
    --lambda_expert_ortho 0.02 ^
    --use_infonce ^
    --focal_gamma 1.0 ^
    --early_stopping_patience 40 ^
    --lr 0.000300 ^
    --seed 42 ^
    --batch_size 48 ^
    --scheduler_type cosine_restarts ^
    --t_mult 2 ^
    --warmup_epochs 20 ^
    --eval_every 5 ^
    --save_every 25 ^
    --output_dir artifacts\best_autotune ^
    --results_json artifacts\best_autotune\results.json ^
    --device auto ^
    --amp

pause